### ISSUE TITLE
Crash on Mac

### ISSUE THREAD

**Issue by LordHeinrich** [tizian/Cendric2#102] opened 2017-11-13 12:55 UTC
Loaded a save in the howling cave (hüülendi höhli) and tried to equip a torch, when the game client crashed. Copied the crash log and restarted the game, which crashed again once I tried to equip the torch. 

[Crash Log.pdf](https://github.com/tizian/Cendric2/files/1466874/Crash.Log.pdf)

**Comment by Ironbell** [comment] 2017-11-14 17:08
Could you tell us your specs (OS Version, Graphics Card)? We tried to reproduce it on mac but failed.

**Comment by Ironbell** [comment] 2017-11-14 17:18
Also, could you list the exact steps to get there? Was it only going into the cave and then equip the torch?

**Comment by LordHeinrich** [comment] 2017-11-14 19:44
OSX Mac OS High Sierra
Gpu: Intel Iris Graphics 6100 1536MB
Memory: 8 GB 1867 MHz DDR3
Processor: 3.1 GHz Intel Core i7

I didnt walk into the cave, I loaded the game and was at one of the checkpoints (the one with the wolf to the right of it) killed the wolf, walked to the right to the ledge, went into my inventory dragged the torch to the weapon equip slot and then the game crashed.
Reloaded and did the same thing again, game crashed again.

**Comment by LordHeinrich** [comment] 2017-11-14 20:43
Just happened again, Mines of Gandria, equipped the pickaxe then the game crashed. This time I didnt load inside the cave though

**Comment by Ironbell** [comment] 2017-11-14 22:37
I might have fixed something with equipping  weapons now but it's really hard for me as I don't have a mac and the guy with the mac is also not able to reproduce it. Maybe you can try again in the next build and see whether it persists.

**Comment by LordHeinrich** [comment] 2017-11-15 07:05
Sure I'll do that, the bug Isn't serious anyway, as the game saves whenever you enter a level

**Comment by Ironbell** [comment] 2017-11-15 07:19
A crash is a serious bug nonetheless ;) thank you for reporting it.

**Comment by Ironbell** [comment] 2017-11-19 08:41
This has been most likely closed in #106

**Closed by Ironbell** 2017-11-19 08:41 UTC
Labels: crash, not reproducible, os: mac
