### ISSUE TITLE
Alt Tab doesn't really work.

### ISSUE THREAD

**Issue by Auronit** [tizian/Cendric2#33] opened 2017-11-09 21:15 UTC
When playing a game I often find myself Alt-Tabbing out of it. This is a little messed up here, as the screen is suddenly very compromised (there's a huge black border, so not just the resolution has gone down btu the actual screen size.

**Comment by Ironbell** [comment] 2017-11-09 21:17
What's your OS and setup? (monitor-wise)

**Comment by Ironbell** [comment] 2017-11-09 22:28
Thank you. Playing in full screen or full window or windowed fullscreen mode? :P

**Comment by Auronit** [comment] 2017-11-09 22:37
I was playing in fullscreen there. Windowed is fine

**Comment by Ironbell** [comment] 2017-11-25 22:46
Alt-Tab works fine for me (Windows 10). As I can't reproduce it on my system and it's an annoying but rather small problem, I will look at it only if there's enough time before the release

![unbenannt](https://user-images.githubusercontent.com/9303244/33235555-a854c056-d23a-11e7-9f5a-6e8fec6309a0.png)

**Comment by Ironbell** [comment] 2017-12-03 12:47
Auronit, I need your email address for your points :)

**Comment by Auronit** [comment] 2017-12-05 19:56
sikiobasel@gmail.com

Terribly sorry, I've had some rough weeks.

**Comment by Ironbell** [comment] 2018-03-12 13:21
I will close this as this seems to be no longer an issue. Feel free to reopen if it occurs (and specify the system specs).

**Closed by Ironbell** 2018-03-12 13:21 UTC
Labels: SFML
