### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by nickydickydoo** [tizian/Cendric2#106] opened 2017-11-16 03:03 UTC
The game crashed for me in The Howling Caverns. I was able to reproduce the crash several times. So I had the Hawthorn equipped, and with it the Iceball and Count gem. I go to my inventory and equip the Mace of the Order, and then pair the Iceball with that. After that go back to inventory and equip the Hawthorn again. Then try going to gems and the game will crash. Even if I unequip the Iceball before switching tothe Mace the crash will still happen. I have only tested this on Windows.

**Comment by Ironbell** [comment] 2017-11-16 07:29
I'm pretty sure this issue will already be fixed in the fresh build tonight because I found this crash as well (while trying to reproduce #102). But you still wrote up the steps perfectly to reproduce it. You'll get points regardless of the potential duplicate :)

**Closed** 2017-11-16 18:18 UTC
Labels: crash, duplicate
