### ISSUE TITLE
Ingrids Eintopf Bug Mac

### ISSUE THREAD

**Issue by LordHeinrich** [tizian/Cendric2#103] opened 2017-11-13 13:54 UTC
Drank Ingrids eintopf in the Howling cave, my health is decreasing into the negative spectrum but I am not dying.

**Comment by Ironbell** [comment] 2017-11-13 14:01
Negative Health is fixed by now (see #66) and also in the next build. The Eintopf bug is new though.

**Comment by Ironbell** [comment] 2017-11-14 20:01
Can't reproduce on windows. We got no uninitialized variables here. @tizian ?

**Comment by Ironbell** [comment] 2017-11-22 22:15
Is not reproducible.  If it occurs again in a newer build, please reopen.

**Closed by Ironbell** 2017-11-22 22:15 UTC
Labels: not reproducible, os: mac, serious bug
